// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		AAvatar: typeof import('ant-design-vue/es')['Avatar'];
		AButton: typeof import('ant-design-vue/es')['Button'];
		ACard: typeof import('ant-design-vue/es')['Card'];
		ACheckbox: typeof import('ant-design-vue/es')['Checkbox'];
		ACheckboxGroup: typeof import('ant-design-vue/es')['CheckboxGroup'];
		ACol: typeof import('ant-design-vue/es')['Col'];
		ADatePicker: typeof import('ant-design-vue/es')['DatePicker'];
		AForm: typeof import('ant-design-vue/es')['Form'];
		AFormItem: typeof import('ant-design-vue/es')['FormItem'];
		AInput: typeof import('ant-design-vue/es')['Input'];
		ALayout: typeof import('ant-design-vue/es')['Layout'];
		ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
		ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
		ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
		AMenu: typeof import('ant-design-vue/es')['Menu'];
		AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
		AModal: typeof import('ant-design-vue/es')['Modal'];
		ARadio: typeof import('ant-design-vue/es')['Radio'];
		ARadioButton: typeof import('ant-design-vue/es')['RadioButton'];
		ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup'];
		ARow: typeof import('ant-design-vue/es')['Row'];
		ASelect: typeof import('ant-design-vue/es')['Select'];
		ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
		ASwitch: typeof import('ant-design-vue/es')['Switch'];
		ATable: typeof import('ant-design-vue/es')['Table'];
		CodeEditor: typeof import('./components/CodeEditor.vue')['default'];
		HelloWorld: typeof import('./components/HelloWorld.vue')['default'];
	}
}

export {};
