// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AnnotationConfig: typeof import('./pages/visual/components/configs/AnnotationConfig.vue')['default']
    AxisConfig: typeof import('./pages/visual/components/configs/AxisConfig.vue')['default']
    BaseConfig: typeof import('./pages/visual/components/configs/BaseConfig.vue')['default']
    ChartConfig: typeof import('./pages/visual/components/ChartConfig.vue')['default']
    ChartDisplay: typeof import('./pages/visual/components/views/ChartDisplay.vue')['default']
    ChartGrid: typeof import('./pages/visual/components/views/ChartGrid.vue')['default']
    ChartSelect: typeof import('./pages/visual/components/ChartSelect.vue')['default']
    CodeEditor: typeof import('./components/CodeEditor.vue')['default']
    DataTable: typeof import('./pages/publish/components/DataTable.vue')['default']
    ExportGroupByType: typeof import('./pages/publish/ExportGroupByType.vue')['default']
    FieldDefine: typeof import('./pages/preproccess/preproccess/FieldDefine.vue')['default']
    FieldSelect: typeof import('./pages/preproccess/preproccess/FieldSelect.vue')['default']
    FieldSift: typeof import('./pages/preproccess/preproccess/FieldSift.vue')['default']
    HandleFile: typeof import('./pages/start/components/HandleFile.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Image: typeof import('./pages/publish/components/Image.vue')['default']
    KeyConfig: typeof import('./pages/visual/components/configs/KeyConfig.vue')['default']
    LegendConfig: typeof import('./pages/visual/components/configs/LegendConfig.vue')['default']
    LineConfig: typeof import('./pages/visual/components/configs/charts/LineConfig.vue')['default']
    MultipleForm: typeof import('./pages/publish/components/MultipleForm.vue')['default']
    OtherConfig: typeof import('./pages/visual/components/configs/OtherConfig.vue')['default']
    SelectSample: typeof import('./pages/start/components/SelectSample.vue')['default']
    TableEdit: typeof import('./components/TableEdit.vue')['default']
    TableEditor: typeof import('./pages/preproccess/preproccess/TableEditor.vue')['default']
    TextAnnotationConfig: typeof import('./pages/visual/components/configs/annotation/TextAnnotationConfig.vue')['default']
    TextArea: typeof import('./pages/start/components/TextArea.vue')['default']
    Undefined: typeof import('./pages/index.vue')['default']
    Visual: typeof import('./pages/visual/visual.vue')['default']
    WaterMark: typeof import('./components/WaterMark.vue')['default']
    WaterMarkConfig: typeof import('./pages/visual/components/configs/WaterMarkConfig.vue')['default']
  }
}

export { }
