/*
 * @Author: Merlin218
 * @Date: 2022-02-02 12:35:07
 * @LastEditors: Merlin218
 * @LastEditTime: 2022-02-02 12:35:39
 * @Description: 请填写简介
 */
// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
	export interface GlobalComponents {
		AAvatar: typeof import('ant-design-vue/es')['Avatar'];
		AButton: typeof import('ant-design-vue/es')['Button'];
		ACol: typeof import('ant-design-vue/es')['Col'];
		ACollapse: typeof import('ant-design-vue/es')['Collapse'];
		ACollapsePanel: typeof import('ant-design-vue/es')['CollapsePanel'];
		ADivider: typeof import('ant-design-vue/es')['Divider'];
		AForm: typeof import('ant-design-vue/es')['Form'];
		AFormItem: typeof import('ant-design-vue/es')['FormItem'];
		AInput: typeof import('ant-design-vue/es')['Input'];
		AInputNumber: typeof import('ant-design-vue/es')['InputNumber'];
		ALayout: typeof import('ant-design-vue/es')['Layout'];
		ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent'];
		ALayoutFooter: typeof import('ant-design-vue/es')['LayoutFooter'];
		ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader'];
		AMenu: typeof import('ant-design-vue/es')['Menu'];
		AMenuItem: typeof import('ant-design-vue/es')['MenuItem'];
		AnnotationConfig: typeof import('./pages/visual/components/configs/annotation-config/annotation-config.vue')['default'];
		APopconfirm: typeof import('ant-design-vue/es')['Popconfirm'];
		ARadio: typeof import('ant-design-vue/es')['Radio'];
		ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup'];
		ARow: typeof import('ant-design-vue/es')['Row'];
		ASelect: typeof import('ant-design-vue/es')['Select'];
		ASelectOption: typeof import('ant-design-vue/es')['SelectOption'];
		ASwitch: typeof import('ant-design-vue/es')['Switch'];
		AxisConfig: typeof import('./pages/visual/components/configs/axis-config/axis-config.vue')['default'];
		BaseConfig: typeof import('./pages/visual/components/configs/base-config/base-config.vue')['default'];
		ChartDisplay: typeof import('./pages/visual/components/views/chart-display/chart-display.vue')['default'];
		ChartsConfig: typeof import('./pages/visual/components/configs/charts-config/charts-config.vue')['default'];
		CodeEditor: typeof import('./pages/publish/components/CodeEditor.vue')['default'];
		DataTable: typeof import('./pages/publish/components/DataTable.vue')['default'];
		ExportGroupByType: typeof import('./pages/publish/ExportGroupByType.vue')['default'];
		HelloWorld: typeof import('./components/HelloWorld.vue')['default'];
		Image: typeof import('./pages/publish/components/Image.vue')['default'];
		KeyConfig: typeof import('./pages/visual/components/configs/key-config/key-config.vue')['default'];
		LegendConfig: typeof import('./pages/visual/components/configs/legend-config/legend-config.vue')['default'];
		LineConfig: typeof import('./pages/visual/components/configs/charts-config/line-config/line-config.vue')['default'];
		MultipleForm: typeof import('./pages/publish/components/MultipleForm.vue')['default'];
		SelectChart: typeof import('./pages/visual/components/configs/select-chart/select-chart.vue')['default'];
		TextAnnotationConfig: typeof import('./pages/visual/components/configs/annotation-config/text-annotation-config/text-annotation-config.vue')['default'];
		Undefined: typeof import('./pages/index.vue')['default'];
		Visual: typeof import('./pages/visual/visual.vue')['default'];
	}
}

export {};
